sudo: required
dist: trusty
language: generic
cache:
  directories:
    - $HOME/.ccache
addons:
  apt:
    packages:
      - genisoimage
install: bash -ex ./.travis-install.sh
script: bash -ex ./.travis-script.sh

env:
  global:
      - PATH="/usr/lib/ccache:$PATH"
  matrix:
    - PACKAGE=erlang
    - PACKAGE=haproxy
    - PACKAGE=hiawatha
    - PACKAGE=leveldb
    - PACKAGE=libcurl
    - PACKAGE=libevent
    - PACKAGE=libressl
    - PACKAGE=libxml2
    - PACKAGE=mathopd
    - PACKAGE=memcached
    - PACKAGE=mpg123
  # broken: issue #106
  #  - PACKAGE=mysql
    - PACKAGE=nanomsg
    - PACKAGE=nginx
    - PACKAGE=ngircd
    - PACKAGE=nodejs
  # broken: issue #92
  #  - PACKAGE=openmp
    - PACKAGE=pcre
    - PACKAGE=php5
    - PACKAGE=php7
    - PACKAGE=python3
    - PACKAGE=redis
  # Disabled, does not actually build anything interesting
  #  - PACKAGE=roundcube
    - PACKAGE=ruby
  # Disabled, build takes several hours
  #  - PACKAGE=rust
    - PACKAGE=sqlite
    - PACKAGE=tor
    - PACKAGE=apache2
    - PACKAGE=libffi
    - PACKAGE=openjdk8
    - PACKAGE=ovs
    - PACKAGE=zeromq
  #  - PACKAGE=servus
  #  - PACKAGE=zerobuf

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
