sudo: required
dist: trusty
language: generic
install: bash -ex ./.travis-install.sh
script: bash -ex ./.travis-script.sh

env:
  - PACKAGE=erlang
  - PACKAGE=haproxy
  - PACKAGE=hiawatha
  - PACKAGE=leveldb
  - PACKAGE=libcurl
  - PACKAGE=libevent
  - PACKAGE=libxml2
  - PACKAGE=mathopd
  - PACKAGE=memcached
  - PACKAGE=mpg123
  - PACKAGE=mysql
  - PACKAGE=nanomsg
  - PACKAGE=nginx
  - PACKAGE=ngircd
  - PACKAGE=nodejs
  - PACKAGE=openmp
  - PACKAGE=pcre
  - PACKAGE=php
  - PACKAGE=php7
  - PACKAGE=python3
  - PACKAGE=redis
# Disabled, does not actually build anything interesting
#  - PACKAGE=roundcube
  - PACKAGE=ruby
# Disabled, build takes several hours
#  - PACKAGE=rust
  - PACKAGE=sqlite

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@freelists.org
    on_success: always
    on_failure: always
